"""Add movimientos table

Revision ID: 61d2ab4dfa58
Revises: 10cc7f2ed457
Create Date: 2025-05-07 22:21:23.109658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d2ab4dfa58'
down_revision: Union[str, None] = '10cc7f2ed457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimientos',
    sa.Column('movimiento_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ENTRADA', 'SALIDA', name='tipomovimiento'), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('observaciones', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.medicamento_id'], ),
    sa.PrimaryKeyConstraint('movimiento_id')
    )
    op.create_index(op.f('ix_movimientos_movimiento_id'), 'movimientos', ['movimiento_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_movimiento_id'), table_name='movimientos')
    op.drop_table('movimientos')
    # ### end Alembic commands ###
