"""Add medicamentos table

Revision ID: b6f5d854e465
Revises: 
Create Date: 2025-05-06 15:49:10.880708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f5d854e465'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicamentos',
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=False),
    sa.Column('nombre_generico', sa.String(length=255), nullable=False),
    sa.Column('presentacion', sa.String(length=100), nullable=False),
    sa.Column('concentracion', sa.String(length=100), nullable=False),
    sa.Column('laboratorio', sa.String(length=255), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('requiere_receta', sa.Boolean(), nullable=False),
    sa.Column('unidad_empaque', sa.Integer(), nullable=False),
    sa.Column('via_administracion', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('medicamento_id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refresh_tokens')
    op.drop_table('users')
    op.drop_table('medicamentos')
    # ### end Alembic commands ###
