"""Regenerar tabla user

Revision ID: e5f2139c3827
Revises: e475f7c00b9a
Create Date: 2025-05-09 16:31:03.559099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f2139c3827'
down_revision: Union[str, None] = 'e475f7c00b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('alertas',
    sa.Column('alerta_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('tipo_alerta', sa.String(), nullable=False),
    sa.Column('estado', sa.Enum('Pendiente', 'Resuelta', name='estadoalerta'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.medicamento_id'], ),
    sa.PrimaryKeyConstraint('alerta_id')
    )
    op.create_index(op.f('ix_alertas_alerta_id'), 'alertas', ['alerta_id'], unique=False)
    op.create_table('predicciones',
    sa.Column('prediccion_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('temporada', sa.String(), nullable=False),
    sa.Column('uso_previsto', sa.Integer(), nullable=False),
    sa.Column('uso_predicho', sa.Float(), nullable=False),
    sa.Column('fecha_prediccion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.medicamento_id'], ),
    sa.PrimaryKeyConstraint('prediccion_id')
    )
    op.create_index(op.f('ix_predicciones_prediccion_id'), 'predicciones', ['prediccion_id'], unique=False)
    op.create_table('uso_historico',
    sa.Column('historico_id', sa.Integer(), nullable=False),
    sa.Column('medicamento_id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('temporada', sa.String(), nullable=False),
    sa.Column('uso_previsto', sa.Integer(), nullable=False),
    sa.Column('uso_real', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['medicamento_id'], ['medicamentos.medicamento_id'], ),
    sa.PrimaryKeyConstraint('historico_id')
    )
    op.create_index(op.f('ix_uso_historico_historico_id'), 'uso_historico', ['historico_id'], unique=False)
    op.create_table('historial_alertas',
    sa.Column('historial_id', sa.Integer(), nullable=False),
    sa.Column('alerta_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.Enum('Creada', 'Actualizada', 'Resuelta', 'Eliminada', name='accionhistorial'), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alerta_id'], ['alertas.alerta_id'], ),
    sa.PrimaryKeyConstraint('historial_id')
    )
    op.create_index(op.f('ix_historial_alertas_historial_id'), 'historial_alertas', ['historial_id'], unique=False)
    op.add_column('categorias', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('condiciones', sa.Column('descripcion', sa.String(), nullable=True))
    op.add_column('medicamentos', sa.Column('stock_maximo', sa.Integer(), nullable=True))
    op.add_column('medicamentos', sa.Column('lote', sa.String(), nullable=True))
    op.alter_column('medicamentos', 'precio_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('medicamentos', 'fecha_vencimiento',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('medicamentos', 'requiere_receta',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('medicamentos', 'condicion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('medicamentos', 'tipo_toma_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('idx_medicamentos_precio', table_name='medicamentos')
    op.drop_index('idx_medicamentos_stock', table_name='medicamentos')
    op.drop_constraint('medicamentos_codigo_barras_key', 'medicamentos', type_='unique')
    op.drop_column('medicamentos', 'presentacion')
    op.drop_column('medicamentos', 'codigo_barras')
    op.drop_column('medicamentos', 'unidad_empaque')
    op.drop_column('medicamentos', 'via_administracion')
    op.drop_column('medicamentos', 'concentracion')
    op.drop_index('idx_movimientos_fecha', table_name='movimientos')
    op.drop_index('idx_movimientos_medicamento', table_name='movimientos')
    op.add_column('tipos_toma', sa.Column('descripcion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipos_toma', 'descripcion')
    op.create_index('idx_movimientos_medicamento', 'movimientos', ['medicamento_id'], unique=False)
    op.create_index('idx_movimientos_fecha', 'movimientos', ['fecha'], unique=False)
    op.add_column('medicamentos', sa.Column('concentracion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('medicamentos', sa.Column('via_administracion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('medicamentos', sa.Column('unidad_empaque', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('medicamentos', sa.Column('codigo_barras', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('medicamentos', sa.Column('presentacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('medicamentos_codigo_barras_key', 'medicamentos', ['codigo_barras'])
    op.create_index('idx_medicamentos_stock', 'medicamentos', ['stock_actual'], unique=False)
    op.create_index('idx_medicamentos_precio', 'medicamentos', ['precio_unitario'], unique=False)
    op.alter_column('medicamentos', 'tipo_toma_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medicamentos', 'condicion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('medicamentos', 'requiere_receta',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.alter_column('medicamentos', 'fecha_vencimiento',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('medicamentos', 'precio_unitario',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('medicamentos', 'lote')
    op.drop_column('medicamentos', 'stock_maximo')
    op.drop_column('condiciones', 'descripcion')
    op.drop_column('categorias', 'descripcion')
    op.drop_index(op.f('ix_historial_alertas_historial_id'), table_name='historial_alertas')
    op.drop_table('historial_alertas')
    op.drop_index(op.f('ix_uso_historico_historico_id'), table_name='uso_historico')
    op.drop_table('uso_historico')
    op.drop_index(op.f('ix_predicciones_prediccion_id'), table_name='predicciones')
    op.drop_table('predicciones')
    op.drop_index(op.f('ix_alertas_alerta_id'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
