"""Initial migration

Revision ID: 73a5eed5c292
Revises: 1612fc0ee94d
Create Date: 2025-04-30 23:12:16.540157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73a5eed5c292'
down_revision = '1612fc0ee94d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###